name: Actions workflow

on: [push]

jobs:
    run-github-actions:
      runs-on: ubuntu-latest
      steps:

        - name: List Files
          run: |
            pwd
            ls -a

          #This step will clone your repo into the VM.
          # By defualt will not clone.
        - name: Checkout
          uses: actions/checkout@v1

        - name: List Files
          run: |
            pwd
            ls -a

        - name: Simple JS Action
          id: greet
          uses: actions/hello-world-javascript-action@v1
          with: 
            who-to-greet: Dhoni

        - name: Log Greeting Time
          run: echo "${{ steps.greet.outputs.time }}"
