name: Actions workflow

on:
  push:
    branches:
      - master
      - 'feature/*' #Will match feature/featA, feature/featB
      # WIll not match feature/feat/A
      # Because , '*' will not match the '/'

      #The below will match anything after feature/ ie.
      # Matches feature/feat/A , feature/featureA, feature/featB etc.
      - 'feature/**'
      - '!feature/featC'

    tags:
      - v1
      - v2

    paths:
      - '**.js'
      - '!filename.js'
    
    # paths-ignore:
    #   - "docs/**"



  # pull_request:
  #   branches:
  #     - master


  # schedule: 
  # # Minute Hour DayOfMonth Month DayOfWeek
  #   - cron: "* * * * *"

jobs:
    run-github-actions:
      runs-on: ubuntu-latest
      steps:

        - name: List Files
          run: |
            pwd
            ls -a

          #This step will clone your repo into the VM.
          # By defualt will not clone.
        - name: Checkout
          uses: actions/checkout@v1

        - name: List Files
          run: |
            pwd
            ls -a

        - name: Simple JS Action
          id: greet
          uses: actions/hello-world-javascript-action@v1
          with: 
            who-to-greet: Dhoni

        - name: Log Greeting Time
          run: echo "${{ steps.greet.outputs.time }}"
