name: matrix

on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node_version: [6,8,10,12,14]

        include:
          - os: ubuntu-latest
            node_version: 8
            # This variable would exist only for ubuntu-latest and node version 8
            # For other combinations, it would be null or empty string.
            is_ubuntu_8: "true"

        exclude:
          - os: ubuntu-latest
            node_version: 6
          
          - os: macos-latest
            node_version: 8

      fail-fast: false
    # This value will be grabbed from the matrix
    runs-on: ${{matrix.os}}
    env:
      IS_UBUNTU_8: ${{matrix.is_ubuntu_8}}
    steps:
      - name: Log node version.
        run: node -v 

      - name: Changing node version
        uses: actions/setup-node@v1
        with:
        # We use the matrix context to grab the version.
        # from the node_version array in matrix block
        # Will iterate automatically
          node-version: ${{matrix.node_version}}

      - name: Log node version
        run: node -v
