name: matrix

on: push

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Log node version.
        run: node -v 

      - name: Changing node version
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Log node version
        run: node -v
